---
title: "Screen fmri users for SICNU"
---

```{r}
#| label: setup

library(tidyverse)
source("../R/utils-data.R")
requireNamespace("bit64")
```

```{r}
targets::tar_load(c(users, data_parsed, data_parsed_PIQ, progress))
black <- readxl::read_excel("config/blacklist.xlsx", col_names = "user_name")
config <- read_csv("../config/fmri-screen.csv", show_col_types = F)
check_result_raw <- data_parsed |>
  left_join(config, by = "game_name") |>
  filter(!is.na(method)) |>
  mutate(
    passed = pmap_dbl(
      list(data = raw_parsed, game_name, method, chance),
      check_raw
    )
  )
raw_data_check <- check_result_raw |>
  summarise(n_fail = sum(!passed), n = n(), .by = user_id) |>
  filter(n_fail / n < 0.1)
progress_check <- progress |>
  summarise(n = sum(progress) / 100, .by = user_id) |>
  filter(n > 1)
users |>
  semi_join(progress_check, by = "user_id") |>
  semi_join(raw_data_check, by = "user_id") |>
  anti_join(black, by = "user_name") |>
  select(user_name, user_phone) |>
  writexl::write_xlsx("output/fmri_users_sel.xlsx")
```
