default:
  # put all the required where filters here
  where:
    # examples (you should make sure these filters are valid):
    # - table: course
    #   field: Name
    #   operator: REGEXP
    #   values: .*
    # - table: content
    #   field: Name
    # # operator of `=` or `IN` can be neglected
    #   values:
    #   - 萤火虫
    #   - 超级秒表
    - table: v_organizationuser
      field: OrganizationName
      values: 四川师范大学
    - table: course
      field: Name
      values: [认知实验A, 认知实验B, 认知实验C, 认知实验D, 认知实验E]
