---
title: "Fetch and Pre-process Data"
output: html_document
# redirect output to another folder (default is base_dir/output)
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = fs::path(here::here(), "output"),
      ...
    )
  })
---

```{r setup, include=FALSE}
library(targets)
knitr::opts_chunk$set(echo = TRUE, tar_interactive = FALSE)
targets::tar_unscript()
```

```{targets set-globals, tar_globals=TRUE, include=FALSE}
purrr::walk(fs::dir_ls(here::here("R")), source)
future::plan(future.callr::callr)
search_games_mem <- memoise::memoise(
  tarflow.iquizoo::search_games,
  cache = cachem::cache_disk("~/.cache.tarflow")
)
games <- search_games_mem(config_where = config::get("where"))
tar_option_set(
  package = c("tidyverse", "preproc.iquizoo", "tarflow.iquizoo", "openxlsx"),
  format = "qs",
  imports = "preproc.iquizoo"
)
targets_data <- tarchetypes::tar_map(
  values = games,
  names = game_name_abbr,
  # major targets
  tar_target(data, pickup(query_tmpl_data, config_where_single_game)),
  tar_target(data_parsed, wrangle_data(data)),
  # configurations
  tar_target(
    config_where_single_game,
    insert_where_single_game(config_where, game_id)
  )
)
```

```{targets load-config, include=FALSE}
list(
  tar_target(file_config, "config.yml", format = "file"),
  tar_target(config_where, config::get("where", file = file_config)),
  tar_target(games_req_kb, config::get("require_keyboard"))
)
```

```{targets download-users, include=FALSE}
list(
  tar_target(query_tmpl_users, fs::path("sql", "users.tmpl.sql"), format = "file"),
  tar_target(users, tarflow.iquizoo::pickup(query_tmpl_users, config_where))
)
```

```{targets data-and-scores, include=FALSE}
list(
  tar_target(query_tmpl_scores, fs::path("sql", "scores.tmpl.sql"), format = "file"),
  tar_target(query_tmpl_data, fs::path("sql", "data.tmpl.sql"), format = "file"),
  targets_data,
  tarchetypes::tar_combine(
    data_parsed,
    targets_data$data_parsed
  ),
  tarchetypes::tar_file_read(
    users_project_progress,
    fs::path("sql", "progress.tmpl.sql"),
    read = pickup(!!.x, config_where)
  )
)
```

```{targets prepare-makup, include=FALSE}
list(
  tar_target(
    makeup_details,
    users_project_progress |>
      summarise(n = sum(project_progress) / 100, .by = user_id) |>
      filter(n >= 4) |>
      left_join(data_parsed, by = "user_id") |>
      mutate(
        used_mouse = map2_lgl(
          raw_parsed, game_name,
          check_used_mouse
        )
      ) |>
      filter(game_name %in% games_req_kb, used_mouse) |>
      select(user_id, game_name) |>
      left_join(users, by = "user_id") |>
      mutate(user_sex = c("男", "女")[user_sex]) |>
      summarise(
        n = n(),
        games_make_up = str_c(game_name, collapse = ", "),
        .by = c(user_id, user_name, user_sex, user_dob, user_phone)
      )
  ),
  tar_target(
    file_makeup_details,
    makeup_details |> 
      select(
        姓名 = user_name,
        性别 = user_sex,
        生日 = user_dob,
        补测任务数目 = n,
        补测任务列表 = games_make_up
      ) |> 
      writexl::write_xlsx("makeup/details.xlsx"),
    format = "file"
  ),
  tar_target(
    file_users_makeup,
    makeup_details |> 
      select(姓名 = user_name, 手机号码 = user_phone) |> 
      writexl::write_xlsx("makeup/users.xlsx"),
    format = "file"
  )
)
```

```{r run-pipeline, include=FALSE}
# tar_destroy()
tar_make_future(workers = 8)
```
